### ISSUE TITLE
Refactor dynamic frontend pages to use json or DB

### ISSUE THREAD

**Issue by jmidd2** [Phoenix-Spark/hub#9]
Based on an environment variable such as REACT_APP_STATIC_VERSION conditionally set the fetch URL to fetch either our API or the local file.

**Comment by jmidd2** [comment]
This will require all our fetch requests to be refactored to a custom hook. Instead of individual useEffects for each fetch call;

@Sugarfreeboi [Here are some docs on how to make custom hooks.](https://legacy.reactjs.org/docs/hooks-custom.html)

**Comment by AlexJWhitcomb** [comment]
https://www.youtube.com/watch?v=Jl4q2cccwf0

**Comment by Sugarfreeboi** [comment]
I have the custom hook created. Currently inside the pages directory.

**Comment by jmidd2** [comment]
> I have the custom hook created. Currently inside the pages directory.

Did you push the branch to the repo?

**Comment by Sugarfreeboi** [comment]
Alex, were you able to commit and push last night?

**Comment by jmidd2** [comment]
ce23407 & 8616c7e is a good start to use a custom hook. Now some of the work the API was handling needs to be added. Without the API filtering the data for the frontend. The data filtering will need to done after the file is pulled in.

For example, for the cell details, Cell.js, the data needs to include the users that are assigned to that team and the base's name. Or, on the Hub, the cell data needs to include all base information as well (name, lat, lng).

As an example see f71118c.
